DROP TABLE IF EXISTS mugs CASCADE;

CREATE TABLE mugs (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES sellers(id) ON DELETE CASCADE,
  price INTEGER  NOT NULL DEFAULT 0,
  name VARCHAR(255) NOT NULL,
  quantity INTEGER  NOT NULL DEFAULT 0,
  in_stock BOOLEAN DEFAULT TRUE
);
